/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AnnotationOutput,  BranchOption,  BranchTree,  CommunicationDefaults,  ContextOutput,  MirrorInsight,  MirrorOutput,  ObservedPattern,  PersonaInteraction,  PersonaProfile,  PersonaUpdateOutput,  ScoringConfig,  ScoringThresholds,  ScoringWeights } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface AnnotationOutput {
      annotation?: "-" | "!!" | "!" | "!?" | "?!" | "?" | "??" | null
      label?: string | null
      reason?: string | null
      confidence?: number | null
      matchedRules: string[]
      sessionKey?: string | null
      score?: number | null
    }
    export interface BranchOption {
      optionId?: 1 | 2 | 3 | null
      isRecommended?: boolean | null
      annotation?: "-" | "!!" | "!" | "!?" | "?!" | "?" | "??" | null
      outcomeLabel?: string | null
      moveLabel?: string | null
      message?: string | null
      predictedResponse?: string | null
      opponentMoveType?: string | null
      branchPath?: string | null
      strategicPayoff?: string | null
      goalAlignmentScore?: number | null
      whyItWorks?: string | null
      risk?: string | null
    }
    export interface BranchTree {
      situationRead?: string | null
      contextEvidence: string[]
      toneTarget?: string | null
      primaryGoal?: string | null
      draftAssessment?: AnnotationOutput | null
      branches: BranchOption[]
    }
    export interface CommunicationDefaults {
      formalityRange?: string | null
      humorStyle?: string | null
      emotionalExpression?: string | null
      directness?: string | null
      warmthBaseline?: string | null
    }
    export interface ContextOutput {
      recipientName?: string | null
      recipientHandle?: string | null
      communicationStyle?: "formal" | "casual" | "professional" | "warm" | "terse" | "verbose" | null
      emotionalStateSignals: string[]
      relationshipType?: "stranger" | "acquaintance" | "colleague" | "romantic" | "friend" | null
      platform?: "linkedin" | "twitter" | "gmail" | "dating_app" | "slack" | "other" | null
      threadSummary?: string | null
      recipientLastMessage?: string | null
      inferredWants?: string | null
      inferredConcerns?: string | null
      contextConfidence?: number | null
      currentConversationSummary?: string | null
      recentMessages: string[]
      conversationGoalHint?: string | null
    }
    export interface MirrorInsight {
      insightId?: string | null
      observation?: string | null
      supportingPattern?: string | null
      evidenceCount?: number | null
      confidence?: number | null
      createdAt?: string | null
      status?: "active" | "dismissed" | null
    }
    export interface MirrorOutput {
      shouldSurfaceMirror?: boolean | null
      insights: MirrorInsight[]
    }
    export interface ObservedPattern {
      pattern?: string | null
      count?: number | null
      confidence?: number | null
      firstSeenAt?: string | null
      lastSeenAt?: string | null
    }
    export interface PersonaInteraction {
      interactionId?: string | null
      sessionId?: string | null
      platform?: string | null
      preset?: string | null
      draftRaw?: string | null
      draftFinal?: string | null
      chosenOptionId?: number | null
      optionRejectedIds: number[]
      recipientContextHash?: string | null
      outcome?: string | null
      observedSignals: string[]
    }
    export interface PersonaProfile {
      version?: number | null
      confidence?: number | null
      learningPhase?: string | null
      communicationDefaults?: CommunicationDefaults | null
      observedPatterns: ObservedPattern[]
      knownStrengths: string[]
      knownWeaknesses: string[]
      interactionCount?: number | null
      coldStartContext?: "dating" | "professional" | "general" | null
      lastUpdated?: string | null
      lastMirrorAt?: string | null
    }
    export interface PersonaUpdateOutput {
      updatedPersona?: PersonaProfile | null
      mirrorInsights: MirrorInsight[]
    }
    export interface ScoringConfig {
      sessionKey?: string | null
      primaryGoal?: string | null
      toneTarget?: string | null
      platform?: string | null
      relationshipType?: string | null
      recipientSensitivity?: number | null
      weights?: ScoringWeights | null
      thresholds?: ScoringThresholds | null
    }
    export interface ScoringThresholds {
      brilliant?: number | null
      good?: number | null
      interesting?: number | null
      dubious?: number | null
      weak?: number | null
    }
    export interface ScoringWeights {
      genericFollowUpPenalty?: number | null
      hedgePenalty?: number | null
      ambiguityPenalty?: number | null
      clarityQuestionBonus?: number | null
      concreteChoiceBonus?: number | null
      nextStepBonus?: number | null
      overlongPenalty?: number | null
      warmthBonus?: number | null
      pressurePenalty?: number | null
    }
}