/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    AnnotationOutput: ClassViewer<'AnnotationOutput', "annotation" | "label" | "reason" | "confidence" | "matchedRules" | "sessionKey" | "score">;
    
    BranchOption: ClassViewer<'BranchOption', "optionId" | "isRecommended" | "annotation" | "outcomeLabel" | "moveLabel" | "message" | "predictedResponse" | "opponentMoveType" | "branchPath" | "strategicPayoff" | "goalAlignmentScore" | "whyItWorks" | "risk">;
    
    BranchTree: ClassViewer<'BranchTree', "situationRead" | "contextEvidence" | "toneTarget" | "primaryGoal" | "draftAssessment" | "branches">;
    
    CommunicationDefaults: ClassViewer<'CommunicationDefaults', "formalityRange" | "humorStyle" | "emotionalExpression" | "directness" | "warmthBaseline">;
    
    ContextOutput: ClassViewer<'ContextOutput', "recipientName" | "recipientHandle" | "communicationStyle" | "emotionalStateSignals" | "relationshipType" | "platform" | "threadSummary" | "recipientLastMessage" | "inferredWants" | "inferredConcerns" | "contextConfidence" | "currentConversationSummary" | "recentMessages" | "conversationGoalHint">;
    
    MirrorInsight: ClassViewer<'MirrorInsight', "insightId" | "observation" | "supportingPattern" | "evidenceCount" | "confidence" | "createdAt" | "status">;
    
    MirrorOutput: ClassViewer<'MirrorOutput', "shouldSurfaceMirror" | "insights">;
    
    ObservedPattern: ClassViewer<'ObservedPattern', "pattern" | "count" | "confidence" | "firstSeenAt" | "lastSeenAt">;
    
    PersonaInteraction: ClassViewer<'PersonaInteraction', "interactionId" | "sessionId" | "platform" | "preset" | "draftRaw" | "draftFinal" | "chosenOptionId" | "optionRejectedIds" | "recipientContextHash" | "outcome" | "observedSignals">;
    
    PersonaProfile: ClassViewer<'PersonaProfile', "version" | "confidence" | "learningPhase" | "communicationDefaults" | "observedPatterns" | "knownStrengths" | "knownWeaknesses" | "interactionCount" | "coldStartContext" | "lastUpdated" | "lastMirrorAt">;
    
    PersonaUpdateOutput: ClassViewer<'PersonaUpdateOutput', "updatedPersona" | "mirrorInsights">;
    
    ScoringConfig: ClassViewer<'ScoringConfig', "sessionKey" | "primaryGoal" | "toneTarget" | "platform" | "relationshipType" | "recipientSensitivity" | "weights" | "thresholds">;
    
    ScoringThresholds: ClassViewer<'ScoringThresholds', "brilliant" | "good" | "interesting" | "dubious" | "weak">;
    
    ScoringWeights: ClassViewer<'ScoringWeights', "genericFollowUpPenalty" | "hedgePenalty" | "ambiguityPenalty" | "clarityQuestionBonus" | "concreteChoiceBonus" | "nextStepBonus" | "overlongPenalty" | "warmthBonus" | "pressurePenalty">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "AnnotationOutput","BranchOption","BranchTree","CommunicationDefaults","ContextOutput","MirrorInsight","MirrorOutput","ObservedPattern","PersonaInteraction","PersonaProfile","PersonaUpdateOutput","ScoringConfig","ScoringThresholds","ScoringWeights",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.AnnotationOutput = this.tb.classViewer("AnnotationOutput", [
          "annotation","label","reason","confidence","matchedRules","sessionKey","score",
        ]);
        
        this.BranchOption = this.tb.classViewer("BranchOption", [
          "optionId","isRecommended","annotation","outcomeLabel","moveLabel","message","predictedResponse","opponentMoveType","branchPath","strategicPayoff","goalAlignmentScore","whyItWorks","risk",
        ]);
        
        this.BranchTree = this.tb.classViewer("BranchTree", [
          "situationRead","contextEvidence","toneTarget","primaryGoal","draftAssessment","branches",
        ]);
        
        this.CommunicationDefaults = this.tb.classViewer("CommunicationDefaults", [
          "formalityRange","humorStyle","emotionalExpression","directness","warmthBaseline",
        ]);
        
        this.ContextOutput = this.tb.classViewer("ContextOutput", [
          "recipientName","recipientHandle","communicationStyle","emotionalStateSignals","relationshipType","platform","threadSummary","recipientLastMessage","inferredWants","inferredConcerns","contextConfidence","currentConversationSummary","recentMessages","conversationGoalHint",
        ]);
        
        this.MirrorInsight = this.tb.classViewer("MirrorInsight", [
          "insightId","observation","supportingPattern","evidenceCount","confidence","createdAt","status",
        ]);
        
        this.MirrorOutput = this.tb.classViewer("MirrorOutput", [
          "shouldSurfaceMirror","insights",
        ]);
        
        this.ObservedPattern = this.tb.classViewer("ObservedPattern", [
          "pattern","count","confidence","firstSeenAt","lastSeenAt",
        ]);
        
        this.PersonaInteraction = this.tb.classViewer("PersonaInteraction", [
          "interactionId","sessionId","platform","preset","draftRaw","draftFinal","chosenOptionId","optionRejectedIds","recipientContextHash","outcome","observedSignals",
        ]);
        
        this.PersonaProfile = this.tb.classViewer("PersonaProfile", [
          "version","confidence","learningPhase","communicationDefaults","observedPatterns","knownStrengths","knownWeaknesses","interactionCount","coldStartContext","lastUpdated","lastMirrorAt",
        ]);
        
        this.PersonaUpdateOutput = this.tb.classViewer("PersonaUpdateOutput", [
          "updatedPersona","mirrorInsights",
        ]);
        
        this.ScoringConfig = this.tb.classViewer("ScoringConfig", [
          "sessionKey","primaryGoal","toneTarget","platform","relationshipType","recipientSensitivity","weights","thresholds",
        ]);
        
        this.ScoringThresholds = this.tb.classViewer("ScoringThresholds", [
          "brilliant","good","interesting","dubious","weak",
        ]);
        
        this.ScoringWeights = this.tb.classViewer("ScoringWeights", [
          "genericFollowUpPenalty","hedgePenalty","ambiguityPenalty","clarityQuestionBonus","concreteChoiceBonus","nextStepBonus","overlongPenalty","warmthBonus","pressurePenalty",
        ]);
        
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}