/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface AnnotationOutput {
  annotation: "-" | "!!" | "!" | "!?" | "?!" | "?" | "??"
  label: string
  reason: string
  confidence: number
  matchedRules: string[]
  sessionKey: string
  score: number
  
}

export interface BranchOption {
  optionId: 1 | 2 | 3
  isRecommended: boolean
  annotation: "-" | "!!" | "!" | "!?" | "?!" | "?" | "??"
  outcomeLabel: string
  moveLabel: string
  message: string
  predictedResponse: string
  opponentMoveType: string
  branchPath: string
  strategicPayoff: string
  goalAlignmentScore: number
  whyItWorks: string
  risk?: string | null
  
}

export interface BranchTree {
  situationRead: string
  contextEvidence: string[]
  toneTarget: string
  primaryGoal: string
  draftAssessment: AnnotationOutput
  branches: BranchOption[]
  
}

export interface CommunicationDefaults {
  formalityRange: string
  humorStyle: string
  emotionalExpression: string
  directness: string
  warmthBaseline: string
  
}

export interface ContextOutput {
  recipientName?: string | null
  recipientHandle?: string | null
  communicationStyle: "formal" | "casual" | "professional" | "warm" | "terse" | "verbose"
  emotionalStateSignals: string[]
  relationshipType: "stranger" | "acquaintance" | "colleague" | "romantic" | "friend"
  platform: "linkedin" | "twitter" | "gmail" | "dating_app" | "slack" | "other"
  threadSummary: string
  recipientLastMessage?: string | null
  inferredWants: string
  inferredConcerns: string
  contextConfidence: number
  currentConversationSummary: string
  recentMessages: string[]
  conversationGoalHint: string
  
}

export interface MirrorInsight {
  insightId: string
  observation: string
  supportingPattern: string
  evidenceCount: number
  confidence: number
  createdAt: string
  status: "active" | "dismissed"
  
}

export interface MirrorOutput {
  shouldSurfaceMirror: boolean
  insights: MirrorInsight[]
  
}

export interface ObservedPattern {
  pattern: string
  count: number
  confidence: number
  firstSeenAt: string
  lastSeenAt: string
  
}

export interface PersonaInteraction {
  interactionId: string
  sessionId: string
  platform: string
  preset: string
  draftRaw: string
  draftFinal: string
  chosenOptionId: number
  optionRejectedIds: number[]
  recipientContextHash: string
  outcome: string
  observedSignals: string[]
  
}

export interface PersonaProfile {
  version: number
  confidence: number
  learningPhase: string
  communicationDefaults: CommunicationDefaults
  observedPatterns: ObservedPattern[]
  knownStrengths: string[]
  knownWeaknesses: string[]
  interactionCount: number
  coldStartContext: "dating" | "professional" | "general"
  lastUpdated: string
  lastMirrorAt?: string | null
  
}

export interface PersonaUpdateOutput {
  updatedPersona: PersonaProfile
  mirrorInsights: MirrorInsight[]
  
}

export interface ScoringConfig {
  sessionKey: string
  primaryGoal: string
  toneTarget: string
  platform: string
  relationshipType: string
  recipientSensitivity: number
  weights: ScoringWeights
  thresholds: ScoringThresholds
  
}

export interface ScoringThresholds {
  brilliant: number
  good: number
  interesting: number
  dubious: number
  weak: number
  
}

export interface ScoringWeights {
  genericFollowUpPenalty: number
  hedgePenalty: number
  ambiguityPenalty: number
  clarityQuestionBonus: number
  concreteChoiceBonus: number
  nextStepBonus: number
  overlongPenalty: number
  warmthBonus: number
  pressurePenalty: number
  
}
